version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.2.2  # Change the Ruby version to match the one in your Gemfile

    steps:
      - checkout

      # Replace the following commands with the necessary steps for setting up your Rails application
      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Database Setup
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Run System Tests
          command: bundle exec rails test:system
